#!/bin/bash

# Define the dir containing hognose
SCRIPT_DIR="$( cd "$(dirname "$0")" ; pwd -P )"

# Check if the dir is already in PATH
if ! echo "$PATH" | grep -q "$SCRIPT_DIR"; then
    # Add the directory to PATH in .bashrc

    echo "  ___ ___                _______                       ";
    echo " /   |   \  ____   ____  \      \   ____  ______ ____  ";
    echo "/    ~    \/  _ \ / ___\ /   |   \ /  _ \/  ___// __ \ ";
    echo "\    Y    (  <_> ) /_/  >    |    (  <_> )___ \\  ___/ ";
    echo " \___|_  / \____/\___  /\____|__  /\____/____  >\___  >";
    echo "       \/       /_____/         \/           \/     \/ ";

    echo "export PATH=\$PATH:$SCRIPT_DIR" >> ~/.bashrc
    echo "HOGNOSE has added to PATH! Enjoy using your new package manager!"
    echo "Please run 'source ~/.bashrc' or restart your terminal."
else
    echo "Hognose is already in PATH."
fi
