#!/bin/bash

# Define the DIR containing Hognose
SCRIPT_DIR="$( cd "$(dirname "$0")" ; pwd -P )"

# Check if the DIR is already in PATH
# Won't work as expected as I've hard coded the path atm because of issues with
# WSL pathing...
if ! echo "$PATH" | grep -q "$SCRIPT_DIR"; then

    # Hognose ASCII Logo
    echo "  ___ ___                _______                       ";
    echo " /   |   \  ____   ____  \      \   ____  ______ ____  ";
    echo "/    ~    \/  _ \ / ___\ /   |   \ /  _ \/  ___// __ \ ";
    echo "\    Y    (  <_> ) /_/  >    |    (  <_> )___ \\  ___/ ";
    echo " \___|_  / \____/\___  /\____|__  /\____/____  >\___  >";
    echo "       \/       /_____/         \/           \/     \/ ";

    # Adds Hognose to global PATH
    echo "export PATH=\$PATH:$SCRIPT_DIR" >> ~/.bashrc

    # Generates a wrapper function in ~/.bashrc to handle 
    # Hognose (commands->scripts) that require eval for 'source'
    # So the command runs in the main shell rather than a subshell
    # NEED TO CHANGE PATHING LATER FOR USER SPECIFIC PATH! (WSL ISSUES)
    echo "hognose() {
        local cmd
        cmd=\$(/mnt/c/Users/louis/hognose/hognose \"\$@\")
        if [[ \"\$1\" == \"activate\" ]]; then
            eval \"\$cmd\"
        elif [[ \"\$1\" == \"deactivate\" ]]; then
            eval \"\$cmd\"
        else
            echo \"\$cmd\"
        fi
    }" >> ~/.bashrc

    # Welcome Message
    echo "HOGNOSE has added to PATH! Enjoy using your new package manager!"
    echo "Please run 'source ~/.bashrc' or restart your terminal."
else
    echo "Hognose is already in PATH."
fi


